import random
from sympy import *
from primeGeneration import generateLargePrime
def generateKeys(primeBits):
    #Just to note, I don't have to use .random to generate these values, I could use a true random number generator, as it is for their keys.
    #Bob's private and public key generation
    p=generateLargePrime(primeBits)#If this is 100, I think the shared key will always be the same length
    bobPrivateKey=random.randint(200,6000)#Bob's private key(sk), large random integer. (z_p)

    xValue=random.randint(10,100)#Another integer with same restrictions as sk
    Tsk=chebyshevt(bobPrivateKey,xValue)%p#Calculates the Chebyshev polynomial of the first kind, where n is Bob's private key, and the value of x is xvalue, mod p.

    Usk=chebyshevu(bobPrivateKey-1,xValue)%p#Calculates the Chebyshev polynomial of the second kind, where n is Bob's private key-1 and the value of x is xvalue, mod p
    bobPublicKey=(p,xValue,Tsk,Usk)


    # print("Done generating Bob's keys")

    #Alice's shared secret generation
    ek=random.randint(200,6000)#This would be a large random integer with the restrictions to Z_p, ek is the ephemeral key

    Uek=chebyshevu(ek-1,bobPublicKey[2])%p#Calculates the Chebyshev polynomial of the second kind where n is ek-1 and the x value is Tsk, mod p
    AliceSharedKey=((Uek%p)*bobPublicKey[3])%p#The shared key generated by Alice
    # print("Done generating Alice's shared secret")

    Tek=chebyshevt(ek,xValue)%p#Calculates the Chebyshev polynomial of the first kind where n is ek and x is xvalue, mod p

    AliceSendToBob=(Tek,chebyshevu(ek-1,xValue)%p)#What Alice will send to Bob, for Bob to generate his shared key. She can't explicitley send the shared key
    
    # print("Doen generating what Alice will send to Bob")

    #Bob's shared secret generation
    UskT=chebyshevu(bobPrivateKey-1,AliceSendToBob[0])%p
    BobSharedKey=(UskT*AliceSendToBob[1])%p
    return (bobPublicKey, BobSharedKey)

    # print(AliceSharedKey)
    # print(BobSharedKey)
    # print(bobPublicKey)